# Server settings  
server:  
    port:8080
    address:localhost  

# DATASOURCE  
jdbc:
    driverClass: com.mysql.jdbc.Driver
#production environment
#    url: jdbc:mysql://rdsh0t197b6ly9dth6c5.mysql.rds.aliyuncs.com:3306/fuelagent?useUnicode=true&characterEncoding=UTF-8
#    username: fuelagent
#    password: j5xZ9aAon
#test environment
    url: jdbc:mysql://172.16.1.157:3306/crawl?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 63TlLScUogSr
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 3600
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

spring:
    freemarker:
          cache=false

#redis:
#    url: 172.16.1.143:6380
      
#logging
logging:
    file: log/g7_crawl.log
#    file:  ${user.dir}/log/g7_crawl.log
    level: INFO
